// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzdwvslheirpdvxvkwyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6ZHd2c2xoZWlycGR2eHZrd3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjI5MjEsImV4cCI6MjA2MzkzODkyMX0.whZvhTV-1iO-CDa1qFPu6nTxMr3bDOFAMrSZYijdrUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);